---
hostname: spine2

cli:
  host: "{{ ansible_host }}"
  username: "{{ dellos10_cli_user | default('admin') }}"
  password: "{{ dellos10_cli_pass | default('admin') }}"
  timeout: 300

# This section is for copying running config to remote location
copy_running_remote:
    - copy_type: scp
      username: linuxadmin
      password: linuxadmin
      host_ip: 10.16.204.62
      file_path: /home/linuxadmin/running_config


dellos_bgp:
    asn: 64901
    router_id: 100.0.1.2
    neighbor:
      - type: ipv4
        remote_asn: 64801
        ip: 100.2.1.2
        admin: down
        state: present
      - type: ipv4
        remote_asn: 64802
        ip: 100.2.33.2
        admin: down
        state: present
      - type: ipv4
        remote_asn: 64803
        ip: 100.2.17.2
        admin: down
        state: present
      - type: ipv4
        remote_asn: 64804
        ip: 100.2.49.2
        admin: down
        state: present		
      - type: ipv6
        remote_asn: 64801
        ip: 2001:100:2:1::2
        admin: down
        state: present
      - type: ipv6
        remote_asn: 64802
        ip: 2001:100:2:11::2
        admin: down
        state: present
      - type: ipv6
        remote_asn: 64803
        ip: 2001:100:2:21::2
        admin: down
        state: present
      - type: ipv6
        remote_asn: 64804
        ip: 2001:100:2:31::2
        admin: down
        state: present		
    state: present
